### ISSUE TITLE
コメント投稿APIのドキュメントを書く

### ISSUE THREAD

**Issue by shoma2da** [handshakejp/user-api#15]
https://hackpad.com/

**Comment by shoma2da** [comment]
http://apiary.io/ に書いていきます。

**Comment by shoma2da** [comment]
@himaratsu できました！内容の確認お願いしますm(_ _)m
http://docs.handshakejp.apiary.io/#

**Comment by himaratsu** [comment]
@shoma2da 確認しました！いいとおもいます！

ホスト名のとこ本番サーバーのに変えるのは最後にやる感じかな？

**Comment by shoma2da** [comment]
> ホスト名のとこ本番サーバーのに変える
やらなきゃ！そこだけ変えときます。

**Comment by shoma2da** [comment]
変えたので閉じますー！
