### ISSUE TITLE
APIをパス設計を全体を通して考える

### ISSUE THREAD

**Issue by shoma2da** [handshakejp/user-api#19]
* dashboard-api
* user-api

**Comment by shoma2da** [comment]
案書きます。変更したほうが良さそうに感じたものだけ書き出してます。

==========================================
【user-api】 http://docs.handshakejpuserapi.apiary.io/

・コメントを投稿する
`http://handshakejp-user-api.herokuapp.com/v1/apikeys/{apikey}/comments`
body
```
{
  "app_version": "1.0.0",
  "device_os": "Android",
  "device_name": "Nexus5",
  "comment_content": "test from api"
}
```
→apikeyをbodyからURLパス内に移動した

・[変更あり]ヘルプ一覧を取得する
`http://handshakejp-user-api.herokuapp.com/v1/apikeys/{apikey}/helps`
→apikeyをURLパラメータからURLパス内に移動したい

=================
【dashboard-api】 http://docs.handshakedashboardapi.apiary.io/#

・ユーザが登録したアプリ一覧取得
`http://handshake-dashboard-api.herokuapp.com/user/{user_id}/applications`
→主体が「ユーザ」なので、URLパスをapplicationと入れ替え
==========================================

ほぼuser-apiだけですねw
エントリポイントはdashboard-apiの方が多かったけど良い感じ！！

**Comment by shoma2da** [comment]
@himaratsu 確認お願いします！

**Comment by shoma2da** [comment]
（これぐらいの軽めの変更だったら確認なしでも良いかもねw　もし見れないようでも次に作業入るときは上記で進めちゃいます！）

**Comment by himaratsu** [comment]
確認OKです！

**Comment by shoma2da** [comment]
見ました！マージOKです！！
