### ISSUE TITLE
Slack 連携

### ISSUE THREAD

**Issue by himaratsu** [handshakejp/user-api#27]
新着でコメントが投稿されたら登録している Slack のチャンネルに内容とパーマネントリンクを投稿する機能をつけたい。

**Comment by shoma2da** [comment]
Done！ https://github.com/handshakejp/user-api/pull/30
通知の実装は別リポジトリです → https://github.com/handshakejp/notifier/pull/5

**Comment by shoma2da** [comment]
閉じちゃいます
